name: Build Mod
on: [push, pull_request] # Собирать при каждом обновлении кода

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 # Для версии 1.21 нужна именно 21 Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradle executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SuperMod-JAR
          path: build/libs/*.jar
    
